### PR TITLE
Cryptodome

### PR DESCRIPTION
**Pull request by sycdan**
The PyCrypto library is no longer maintained, and doesn't officially support Python > 3.2. PyCryptodome is a drop-in replacement which has better compatibility and is actively supported.

### CODE REVIEW

**Comment by tbarn** [comment]
@sycdan Thanks for the PR! We super appreciate it. 🎉 

I'll work on getting it reviewed by the team. :)

**Comment by josephwegner** [comment]
@tbarn FYI this is reviewed and ready to go. Just need @dkador to merge and push it to pypi.

**Comment by dkador** [comment]
@sycdan - I'm ready to merge this, but I was hoping to get #98 in there too. Unfortunately it looks like that's got a broken run for Python 3.2, which looks related to `requests`. Looks like you may have addressed that here? Can you help me understand the state of these PRs? Once I get that I can cut a new version and get this released.

**Comment by sycdan** [comment]
@dkador Yep, you're right: the only reason #98 failed is because `requests` 2.11.0 (released a week ago) is broken in py3, and I didn't bother duplicating 5706ab3 in that PR. I'm quite sure that if you merge this PR in, #98 will be able to pass all the checks and can be merged in after.

**Comment by dkador** [comment]
@sycdan Great, thank you.

**Comment by dkador** [comment]
@sycdan This is now live in 0.3.25.

**Comment by sycdan** [comment]
@dkador Great. Thank you!

**Pull request merged**
