### PR TITLE
Few improvements for Pypi

### PR DESCRIPTION
**Pull request by browniebroke**
- Add classifiers
- Readme in RST format so that it shows better on pypi

### CODE REVIEW

**Comment by stroud109** [comment]
Good call! Thanks @browniebroke 👍

**Comment by browniebroke** [comment]
Another approach for the readme is to use [pandoc](https://pypi.python.org/pypi/pypandoc) in the setup.py, if you guys prefer Markdown over RST?

**Comment by stroud109** [comment]
Thanks so much for sharing that resource @browniebroke. 

Any chance you could resolve the merge conflict?

**Comment by browniebroke** [comment]
Should be better now.

**Comment by stroud109** [comment]
Woo! PyPi looks so much better: https://pypi.python.org/pypi/keen/ Thank you :)

**Pull request merged**
