### PR TITLE
Add Master key to keen library

### PR DESCRIPTION
**Pull request by ruleant**
It would be convenient to store and/or access the Master API Key using `keen.master_key` or `KEEN_MASTER_KEY` or optionally when creating an instance of `KeenClient()` with

```python
    from keen.client import KeenClient

    client = KeenClient(
        project_id="xxxx",
        write_key="yyyy",
        read_key="zzzz",
        master_key="abcd"
    )
```
In this pull request are 4 commits : 

- https://github.com/ruleant/KeenClient-Python/commit/9edbf53c8f872d90d99ed3887e30aefa5c557c3e : importing `KEEN_MASTER_KEY`
- https://github.com/ruleant/KeenClient-Python/commit/afab4935fe9d736d9626e7fc5ee8ba29026291a2 : (optional) define `master_key` in the KeenApi constructor
- https://github.com/ruleant/KeenClient-Python/commit/2c617e6395343843d8fea4332edaf57a2a452852 : (optional) define `master_key` in the KeenClient constructor
- https://github.com/ruleant/KeenClient-Python/commit/c3a6da471acadf380166fca0e9a0fc13c155740a : (optional) create KeenClient instance with `master_key` parameter

I'm not sure if it is needed to have `master_key` defined in `KeenClient` or `KeenApi`, it surely isn't needed to use the API, but I've added those commits for completeness, I can remove them from this pull request later on.

But I feel it makes sense to have `keen.master_key` defined.
`scoped_keys.encrypt()` could use the `keen.master_key` if parameter `api_key` is not defined?

What do you think?

### CODE REVIEW

**Comment by ruleant** [comment]
added a 5th commit, to fix a typo

**Comment by dzello** [comment]
Hey @ruleant! Thanks for sending the PR. Expect some follow-ups soon.

**Comment by stroud109** [comment]
Thanks Dieter! Looks good. Future SDK functionality, like deletes and getting schema, will be able to take advantage of the master_key too. This should make using scoped keys methods more straightforward :)

**Comment by stroud109** [comment]
Would you mind writing a few test cases that cover the functionality that you've added?

**Comment by ruleant** [comment]
Glad you like my patch. I'll have a look at adding some tests, wanted to
make sure you were going to accept my implementation before writing, before
adding tests and documentation.

**Comment by ruleant** [comment]
@stroud109 I added tests and documentation. Feel free to merge. :)

BTW : the failed test is not the one I added. (see Travis CI logs, it has something to do with a a reset connection to api.keen.io; this tests seems unstable because it failed in previous CI builds as well (across python versions)).

**Comment by stroud109** [comment]
This is looking great, @ruleant! Thanks so much! I've noticed the failing tests too, which is why I just refactored them to include mocking. Want to give me access to your fork so I can mock the tests you just added? Once that's done, I'll merge it in :smile:

**Comment by stroud109** [comment]
Actually @ruleant, would you mind rebasing your branch onto the current state of master? Or, if need be, merging it and resolving any conflicts? Master has the test updates I’ve made and that should be the best way to make sure they’re reflected here and working before we merge back in.

**Comment by ruleant** [comment]
merged with changes in the master branch, adopted tests to take 'post' parameter, and they pass. :)

Not sure this is the right way to go, though. My tests don't need the response mock, because they just test if the applied parameter values are correctly set in the respective object instances, no calls to the API are made.
Maybe the unit tests for KeenClient should be seperated from interaction tests with the API?

**Comment by stroud109** [comment]
Awesome! I think splitting out the tests is a great idea -- maybe that'll be step 2 of the test refactor :stuck_out_tongue: Thanks so much for your patience. Message me at stephanie [at] keen [dot] io, I'd love to send you a gift for your contribution.

**Pull request merged**
