### PR TITLE
Add docs Data Enrichment

### PR DESCRIPTION
**Pull request by mamat-rahmat**
Fixes Issue #107

### CODE REVIEW

**Comment by tbarn** [comment]
Hey @mamat-rahmat! Thanks for the PR! I will get this reviewed tomorrow morning or Monday.

**Comment by tbarn** [comment]
Hey @mamat-rahmat! I'm making a tiny change to some of the wording. It is more from a Keen IO product explanation perspective, so hopefully, it will be clearer to you too.

**Comment by tbarn** [comment]
@mamat-rahmat please fill out this form for your shirt 🎉 https://goo.gl/forms/w3HK9LWeau1UbZwl2

**Comment by mamat-rahmat** [comment]
@tbarn Filled, Thanks!

**Pull request merged**
